export const charactersSeed = [
  {
    id: "original-brandon",
    editionId: "original",
    name: "Brandon Jaspers",
    color: "green",
    speed: [0, 3, 4, 4, 4, 5, 6, 7, 8],
    might: [0, 2, 3, 3, 4, 5, 6, 6, 7],
    sanity: [0, 3, 3, 3, 4, 5, 6, 7, 8],
    knowledge: [0, 1, 3, 3, 5, 5, 6, 6, 7],
    speedStart: 3,
    mightStart: 4,
    sanityStart: 4,
    knowledgeStart: 3,
    age: 12,
    description: "An athletic kid who loves sports.",
  },
  {
    id: "original-peter",
    editionId: "original",
    name: "Peter Akimoto",
    color: "green",
    speed: [0, 3, 3, 3, 4, 6, 6, 7, 7],
    might: [0, 2, 3, 3, 4, 5, 5, 6, 8],
    sanity: [0, 3, 4, 4, 4, 5, 6, 6, 7],
    knowledge: [0, 3, 4, 4, 5, 6, 7, 7, 8],
    speedStart: 4,
    mightStart: 3,
    sanityStart: 4,
    knowledgeStart: 3,
    age: 13,
    description: "A bookish boy who is braver than he looks.",
  },
  {
    id: "original-ox",
    editionId: "original",
    name: "Ox Bellows",
    color: "red",
    speed: [0, 2, 2, 2, 3, 4, 5, 5, 6],
    might: [0, 4, 5, 5, 6, 6, 7, 8, 8],
    sanity: [0, 2, 2, 3, 4, 5, 5, 6, 7],
    knowledge: [0, 2, 2, 3, 3, 5, 5, 6, 6],
    speedStart: 5,
    mightStart: 3,
    sanityStart: 3,
    knowledgeStart: 3,
    age: 23,
    description: "A strong, silent football star.",
  },
  {
    id: "original-darrin",
    editionId: "original",
    name: "Darrin \"Flash\" Williams",
    color: "red",
    speed: [0, 4, 4, 4, 5, 6, 7, 7, 8],
    might: [0, 2, 3, 3, 4, 5, 6, 6, 7],
    sanity: [0, 1, 2, 3, 4, 5, 5, 5, 7],
    knowledge: [0, 2, 3, 3, 4, 5, 5, 5, 7],
    speedStart: 5,
    mightStart: 3,
    sanityStart: 3,
    knowledgeStart: 3,
    age: 20,
    description: "A track star and quick thinker.",
  },
  {
    id: "original-zoe",
    editionId: "original",
    name: "Zoe Ingstrom",
    color: "yellow",
    speed: [0, 4, 4, 4, 4, 5, 6, 8, 8],
    might: [0, 2, 2, 3, 3, 4, 4, 6, 7],
    sanity: [0, 3, 4, 5, 5, 6, 6, 7, 8],
    knowledge: [0, 1, 2, 3, 4, 4, 5, 5, 5],
    speedStart: 4,
    mightStart: 4,
    sanityStart: 3,
    knowledgeStart: 3,
    age: 8,
    description: "A brave little girl with a big imagination.",
  },
  {
    id: "original-missy",
    editionId: "original",
    name: "Missy Dubourde",
    color: "yellow",
    speed: [0, 3, 4, 5, 6, 6, 6, 7, 7],
    might: [0, 2, 3, 3, 3, 4, 5, 6, 7],
    sanity: [0, 1, 2, 3, 4, 5, 5, 6, 7],
    knowledge: [0, 2, 3, 4, 4, 5, 6, 6, 6],
    speedStart: 3,
    mightStart: 4,
    sanityStart: 3,
    knowledgeStart: 4,
    age: 9,
    description: "A spunky kid who is tougher than she looks.",
  },
  {
    id: "original-madame-zostra",
    editionId: "original",
    name: "Madame Zostra",
    color: "blue",
    speed: [0, 2, 3, 3, 5, 5, 6, 6, 7],
    might: [0, 2, 3, 3, 4, 5, 5, 5, 6],
    sanity: [0, 4, 4, 4, 5, 6, 7, 8, 8],
    knowledge: [0, 1, 3, 4, 4, 4, 5, 6, 6],
    speedStart: 3,
    mightStart: 4,
    sanityStart: 3,
    knowledgeStart: 4,
    age: 37,
    description: "A mysterious fortune teller.",
  },
  {
    id: "original-vivian",
    editionId: "original",
    name: "Vivian Lopez",
    color: "blue",
    speed: [0, 3, 4, 4, 4, 4, 6, 7, 8],
    might: [0, 2, 2, 2, 4, 4, 5, 6, 6],
    sanity: [0, 4, 4, 4, 5, 6, 7, 8, 8],
    knowledge: [0, 4, 5, 5, 5, 5, 6, 6, 7],
    speedStart: 4,
    mightStart: 3,
    sanityStart: 3,
    knowledgeStart: 4,
    age: 42,
    description: "A retired horror movie actress.",
  },
  {
    id: "original-father-rhinehardt",
    editionId: "original",
    name: "Father Rhinehardt",
    color: "white",
    speed: [0, 2, 3, 3, 4, 5, 6, 7, 7],
    might: [0, 1, 2, 2, 4, 4, 5, 5, 7],
    sanity: [0, 3, 4, 5, 5, 6, 7, 7, 8],
    knowledge: [0, 1, 3, 3, 4, 5, 6, 6, 8],
    speedStart: 3,
    mightStart: 3,
    sanityStart: 5,
    knowledgeStart: 4,
    age: 62,
    description: "A pious man of faith.",
  },
  {
    id: "original-professor-longfellow",
    editionId: "original",
    name: "Professor Longfellow",
    color: "white",
    speed: [0, 2, 2, 4, 4, 5, 5, 6, 6],
    might: [0, 1, 2, 3, 4, 5, 5, 6, 6],
    sanity: [0, 1, 3, 3, 4, 5, 5, 6, 7],
    knowledge: [0, 4, 5, 5, 5, 5, 6, 7, 8],
    speedStart: 4,
    mightStart: 3,
    sanityStart: 3,
    knowledgeStart: 5,
    age: 57,
    description: "An eccentric professor with vast knowledge.",
  },
  {
    id: "original-heather",
    editionId: "original",
    name: "Heather Granville",
    color: "purple",
    speed: [0, 3, 3, 4, 5, 6, 6, 7, 8],
    might: [0, 3, 3, 3, 4, 5, 6, 7, 8],
    sanity: [0, 3, 3, 3, 4, 5, 6, 6, 6],
    knowledge: [0, 2, 3, 3, 4, 5, 6, 7, 8],
    speedStart: 3,
    mightStart: 3,
    sanityStart: 3,
    knowledgeStart: 5,
    age: 18,
    description: "A prom queen with hidden depths.",
  },
  {
    id: "original-jenny",
    editionId: "original",
    name: "Jenny LeClerc",
    color: "purple",
    speed: [0, 2, 3, 4, 4, 4, 5, 6, 8],
    might: [0, 3, 4, 4, 4, 4, 5, 6, 8],
    sanity: [0, 1, 1, 2, 4, 4, 4, 5, 6],
    knowledge: [0, 2, 3, 3, 4, 4, 5, 6, 8],
    speedStart: 4,
    mightStart: 3,
    sanityStart: 5,
    knowledgeStart: 3,
    age: 21,
    description: "A quiet woman with a mysterious past.",
  },
];
