// Betrayal Legacy: Prologue + 13 chapters
// Keeping descriptions spoiler-light — focusing on setup and mechanics, not story reveals
export const hauntsLegacySeed = [
  {
    id: "legacy-prologue", editionId: "legacy", number: 0, name: "The Prologue",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Determined during the chapter. The haunt reveals the traitor based on specific conditions.",
    heroDescription: "Survive the first night in the house and establish your family's legacy.",
    winConditionTraitor: "Varies by chapter outcome.",
    winConditionHero: "Survive and complete the chapter objective.",
    specialRules: "This is a tutorial chapter. Some rules are simplified. Stickers and legacy deck are introduced.",
  },
  {
    id: "legacy-1", editionId: "legacy", number: 1, name: "Chapter 1",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Determined by the haunt revealer's choices during the chapter.",
    heroDescription: "Work together until the haunt is revealed, then complete the chapter objective.",
    winConditionTraitor: "Complete the traitor's secret objective.",
    winConditionHero: "Defeat the threat and complete the heroes' objective.",
    specialRules: "New family heirlooms may be created. Room stickers may be placed. The winner's choices affect future games.",
  },
  {
    id: "legacy-2", editionId: "legacy", number: 2, name: "Chapter 2",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "The traitor is determined by the haunt trigger. Previous game outcomes may affect who becomes the traitor.",
    heroDescription: "The house remembers. Stickers from previous games affect room abilities.",
    winConditionTraitor: "Complete the traitor's objective for this chapter.",
    winConditionHero: "Stop the traitor and survive.",
    specialRules: "Heirlooms from Chapter 1 are available. New cards may be added to or removed from decks.",
  },
  {
    id: "legacy-3", editionId: "legacy", number: 3, name: "Chapter 3",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Traitor determination escalates. Family history begins to matter.",
    heroDescription: "New threats emerge. The house grows more dangerous with each generation.",
    winConditionTraitor: "Fulfill the chapter's traitor objective.",
    winConditionHero: "Complete the heroes' goal before time runs out.",
    specialRules: "A new family generation takes over. Character selection may be influenced by previous chapters.",
  },
  {
    id: "legacy-4", editionId: "legacy", number: 4, name: "Chapter 4",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "The haunt takes a darker turn. Traitor mechanics become more complex.",
    heroDescription: "Heroes must coordinate more carefully. Stakes increase.",
    winConditionTraitor: "Achieve the chapter objective.",
    winConditionHero: "Survive and prevent the traitor's plan.",
    specialRules: "Permanent changes to the board may occur. Some rooms gain or lose properties.",
  },
  {
    id: "legacy-5", editionId: "legacy", number: 5, name: "Chapter 5",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Mid-campaign turning point. The traitor's motivations deepen.",
    heroDescription: "The house's history becomes clearer. Past decisions echo forward.",
    winConditionTraitor: "Complete the escalated traitor objective.",
    winConditionHero: "Uncover the truth and stop the threat.",
    specialRules: "Major legacy deck reveals. The campaign's overarching story becomes apparent.",
  },
  {
    id: "legacy-6", editionId: "legacy", number: 6, name: "Chapter 6",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Traitor mechanics may involve hidden information from the legacy deck.",
    heroDescription: "Heroes gain access to new tools based on previous victories.",
    winConditionTraitor: "Fulfill the chapter's dark objective.",
    winConditionHero: "Use accumulated knowledge to overcome the threat.",
    specialRules: "New persistent effects may be added to the campaign sheet.",
  },
  {
    id: "legacy-7", editionId: "legacy", number: 7, name: "Chapter 7",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "The campaign's second act begins. Betrayal takes new forms.",
    heroDescription: "New generation, new dangers. The house has changed significantly.",
    winConditionTraitor: "Complete the chapter objective.",
    winConditionHero: "Overcome the evolved threat.",
    specialRules: "Significant board state changes. Some tiles may be permanently altered or removed.",
  },
  {
    id: "legacy-8", editionId: "legacy", number: 8, name: "Chapter 8",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Alliances may shift. Previous traitors' families carry a mark.",
    heroDescription: "Trust becomes harder. The house tests old bonds.",
    winConditionTraitor: "Achieve the increasingly difficult traitor goal.",
    winConditionHero: "Survive and protect what remains.",
    specialRules: "Legacy deck instructions may override standard rules for this chapter.",
  },
  {
    id: "legacy-9", editionId: "legacy", number: 9, name: "Chapter 9",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Late-game escalation. The traitor's powers reflect the campaign's accumulated darkness.",
    heroDescription: "Heroes draw on generations of experience. Family heirlooms are critical.",
    winConditionTraitor: "Complete the penultimate traitor objective.",
    winConditionHero: "Prepare for the final confrontation.",
    specialRules: "Critical campaign decisions. Outcomes heavily influence the finale.",
  },
  {
    id: "legacy-10", editionId: "legacy", number: 10, name: "Chapter 10",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "The house's true nature begins to reveal itself.",
    heroDescription: "Everything built across the campaign comes to bear.",
    winConditionTraitor: "Serve the house's ultimate purpose.",
    winConditionHero: "Break the cycle.",
    specialRules: "Major story reveals. Some permanently sealed components may be opened.",
  },
  {
    id: "legacy-11", editionId: "legacy", number: 11, name: "Chapter 11",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "Near the end. The traitor's role may surprise everyone.",
    heroDescription: "Final preparations. Every advantage matters.",
    winConditionTraitor: "Complete the near-final objective.",
    winConditionHero: "Set up for the endgame.",
    specialRules: "Campaign-critical decisions with permanent consequences.",
  },
  {
    id: "legacy-12", editionId: "legacy", number: 12, name: "Chapter 12",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "The penultimate chapter. Betrayal reaches its peak.",
    heroDescription: "Heroes must use everything they've learned across the campaign.",
    winConditionTraitor: "Achieve the dark goal one last time.",
    winConditionHero: "Survive to face the finale.",
    specialRules: "Final legacy deck instructions before the last chapter.",
  },
  {
    id: "legacy-13", editionId: "legacy", number: 13, name: "Chapter 13 — The Finale",
    omenTrigger: null, roomTrigger: null,
    traitorDescription: "The final betrayal. Everything has led to this.",
    heroDescription: "End the house's reign. All campaign history is relevant.",
    winConditionTraitor: "Win the campaign for darkness.",
    winConditionHero: "Win the campaign for the families.",
    specialRules: "Unique finale rules. The winner determines the campaign's ending. The house is scored based on all chapters played.",
  },
];
