export const itemsSeed = [
  // Items
  { id: "original-angel-feather", editionId: "original", name: "Angel Feather", type: "item", description: "A white feather that seems to glow.", effect: "Lose this item instead of taking physical or mental damage. Discard after use." },
  { id: "original-armor", editionId: "original", name: "Armor", type: "item", description: "A suit of tarnished plate armor.", effect: "Any time you take physical damage, take 1 less point of damage." },
  { id: "original-adrenaline-shot", editionId: "original", name: "Adrenaline Shot", type: "item", description: "A syringe filled with a strange liquid.", effect: "Once during your turn, gain 4 to any one trait. At end of turn, lose 4 from that trait." },
  { id: "original-axe", editionId: "original", name: "Axe", type: "item", description: "A sharp woodcutter's axe.", effect: "Add 1 die to Might attack rolls." },
  { id: "original-bell", editionId: "original", name: "Bell", type: "item", description: "A small silver bell.", effect: "Gain 1 Sanity now. Lose 1 Sanity if you lose the bell." },
  { id: "original-blood-dagger", editionId: "original", name: "Blood Dagger", type: "item", description: "A wicked-looking sacrificial dagger.", effect: "Add 1 die to Might attack rolls." },
  { id: "original-bottle", editionId: "original", name: "Bottle", type: "item", description: "An antique bottle with something sloshing inside.", effect: "Once during your turn, drink to gain 1 in a trait of your choice." },
  { id: "original-candle", editionId: "original", name: "Candle", type: "item", description: "A half-melted candle.", effect: "Avoid drawing event cards. Once per turn, negate an event in your room." },
  { id: "original-dark-dice", editionId: "original", name: "Dark Dice", type: "item", description: "A pair of bone dice.", effect: "Once per turn, roll 1 die. Gain that many points in any one trait." },
  { id: "original-dynamite", editionId: "original", name: "Dynamite", type: "item", description: "A bundle of old dynamite.", effect: "Instead of attacking, roll 7 dice. Each adjacent explorer takes damage equal to the result minus their traits." },
  { id: "original-healing-salve", editionId: "original", name: "Healing Salve", type: "item", description: "A jar of pungent ointment.", effect: "Once during your turn, gain 1 in any physical trait." },
  { id: "original-lucky-stone", editionId: "original", name: "Lucky Stone", type: "item", description: "A smooth, warm stone.", effect: "Once per game, reroll any trait roll." },
  { id: "original-medical-kit", editionId: "original", name: "Medical Kit", type: "item", description: "A dusty but usable first-aid kit.", effect: "Once during your turn, heal 1 point of physical damage from yourself or an adjacent explorer." },
  { id: "original-music-box", editionId: "original", name: "Music Box", type: "item", description: "A delicate music box that plays a haunting tune.", effect: "Gain 1 Sanity now. Lose 1 Sanity if you lose the music box." },
  { id: "original-mystical-elevator", editionId: "original", name: "Mystic Slide", type: "item", description: "A strange device.", effect: "Once per turn, move to any explored room on a lower floor." },
  { id: "original-puzzle-box", editionId: "original", name: "Puzzle Box", type: "item", description: "An intricate box with moving parts.", effect: "Once per turn, make a Knowledge roll of 6+ to gain 2 in any trait." },
  { id: "original-rabbit-foot", editionId: "original", name: "Rabbit's Foot", type: "item", description: "A lucky rabbit's foot on a chain.", effect: "Once per turn, reroll 1 die on any roll." },
  { id: "original-revolver", editionId: "original", name: "Revolver", type: "item", description: "A six-shooter with silver bullets.", effect: "You can attack with Speed instead of Might." },
  { id: "original-sacrificial-dagger", editionId: "original", name: "Sacrificial Dagger", type: "item", description: "A ritual blade.", effect: "Add 1 die to Might attack rolls." },
  { id: "original-smelling-salts", editionId: "original", name: "Smelling Salts", type: "item", description: "A vial of acrid salts.", effect: "Once during your turn, gain 1 Knowledge." },

  // Omens
  { id: "original-bite", editionId: "original", name: "Bite", type: "omen", description: "Something bit you.", effect: "Gain 1 Might. Lose 1 Speed. Make a haunt roll." },
  { id: "original-book", editionId: "original", name: "Book", type: "omen", description: "A leather-bound tome.", effect: "Gain 2 Knowledge now. Make a haunt roll." },
  { id: "original-crystal-ball", editionId: "original", name: "Crystal Ball", type: "omen", description: "A glass sphere that shows another place.", effect: "Look at the top tile of any room stack. Make a haunt roll." },
  { id: "original-dog", editionId: "original", name: "Dog", type: "omen", description: "A faithful companion.", effect: "Companion: Speed 3, Might 4, Sanity 4. Make a haunt roll." },
  { id: "original-girl", editionId: "original", name: "Girl", type: "omen", description: "A lost little girl.", effect: "Companion: Speed 4, Might 2, Sanity 5. Make a haunt roll." },
  { id: "original-holy-symbol", editionId: "original", name: "Holy Symbol", type: "omen", description: "A silver cross that gleams.", effect: "Gain 2 Sanity now. Make a haunt roll." },
  { id: "original-madman", editionId: "original", name: "Madman", type: "omen", description: "A raving lunatic clings to you.", effect: "Companion: Might 5, Speed 4. Lose 2 Sanity now. Make a haunt roll." },
  { id: "original-mask", editionId: "original", name: "Mask", type: "omen", description: "A grotesque face covering.", effect: "Gain 2 in any trait. Lose 2 in any other trait. Make a haunt roll." },
  { id: "original-medallion", editionId: "original", name: "Medallion", type: "omen", description: "A heavy gold medallion.", effect: "Gain 1 in any trait. Make a haunt roll." },
  { id: "original-ring", editionId: "original", name: "Ring", type: "omen", description: "An ornate ring with a dark gem.", effect: "Gain 1 in any trait. Make a haunt roll." },
  { id: "original-skull", editionId: "original", name: "Skull", type: "omen", description: "A grinning skull.", effect: "Lose 2 Sanity. Gain 2 Knowledge. Make a haunt roll." },
  { id: "original-spear", editionId: "original", name: "Spear", type: "omen", description: "A rusty but sharp spear.", effect: "Add 2 dice to Might attack rolls. Make a haunt roll." },
  { id: "original-spirit-board", editionId: "original", name: "Spirit Board", type: "omen", description: "A board for contacting the dead.", effect: "Gain 2 Sanity now. Make a haunt roll." },
];
