export const roomsSeed = [
  // Ground floor rooms
  { id: "original-entrance-hall", editionId: "original", name: "Entrance Hall", floor: "ground", description: "The front door of the house.", effect: "Starting tile. No special effect.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-foyer", editionId: "original", name: "Foyer", floor: "ground", description: "A dusty foyer with a grand staircase.", effect: "Starting tile. No special effect.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-grand-staircase", editionId: "original", name: "Grand Staircase", floor: "ground", description: "A sweeping staircase.", effect: "Starting tile. Connects ground floor to upper floor.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-ballroom", editionId: "original", name: "Ballroom", floor: "ground", description: "A once-elegant ballroom.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-charred-room", editionId: "original", name: "Charred Room", floor: "ground", description: "A burned-out room.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-dining-room", editionId: "original", name: "Dining Room", floor: "ground", description: "A long dining table set for guests who never arrived.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-gardens", editionId: "original", name: "Gardens", floor: "ground", description: "Overgrown gardens surround a crumbling fountain.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-kitchen", editionId: "original", name: "Kitchen", floor: "ground", description: "A kitchen with rusted pots and a foul smell.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-patio", editionId: "original", name: "Patio", floor: "ground", description: "An outdoor patio overlooking dead gardens.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-servants-quarters", editionId: "original", name: "Servants' Quarters", floor: "ground", description: "Cramped quarters for long-gone servants.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },

  // Upper floor rooms
  { id: "original-bedroom", editionId: "original", name: "Bedroom", floor: "upper", description: "A musty bedroom.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-chapel", editionId: "original", name: "Chapel", floor: "upper", description: "A small chapel with broken stained glass.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-collapsed-room", editionId: "original", name: "Collapsed Room", floor: "upper", description: "The floor has partially caved in.", effect: "Draw a tile for the basement and put it next to the basement landing. Move to that room.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-gallery", editionId: "original", name: "Gallery", floor: "upper", description: "Portraits of the house's former inhabitants line the walls.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-game-room", editionId: "original", name: "Game Room", floor: "upper", description: "A room full of dusty board games and cards.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-gymnasium", editionId: "original", name: "Gymnasium", floor: "upper", description: "Exercise equipment from another era.", effect: null, hasEvent: false, hasItem: false, hasOmen: true },
  { id: "original-junk-room", editionId: "original", name: "Junk Room", floor: "upper", description: "Piles of discarded objects.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-library", editionId: "original", name: "Library", floor: "upper", description: "Shelves of ancient books.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-master-bedroom", editionId: "original", name: "Master Bedroom", floor: "upper", description: "A large bedroom with a canopy bed.", effect: null, hasEvent: false, hasItem: false, hasOmen: true },
  { id: "original-organ-room", editionId: "original", name: "Organ Room", floor: "upper", description: "A pipe organ plays by itself.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-research-laboratory", editionId: "original", name: "Research Laboratory", floor: "upper", description: "Beakers, test tubes, and strange chemicals.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-tower", editionId: "original", name: "Tower", floor: "upper", description: "A tall tower with a view of the grounds.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-upper-landing", editionId: "original", name: "Upper Landing", floor: "upper", description: "The top of the grand staircase.", effect: "Starting tile. Connects upper floor to ground floor.", hasEvent: false, hasItem: false, hasOmen: false },

  // Basement rooms
  { id: "original-basement-landing", editionId: "original", name: "Basement Landing", floor: "basement", description: "The bottom of a dark staircase.", effect: "Starting tile. Connects to ground floor.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-catacombs", editionId: "original", name: "Catacombs", floor: "basement", description: "Winding tunnels filled with bones.", effect: null, hasEvent: false, hasItem: false, hasOmen: true },
  { id: "original-chasm", editionId: "original", name: "Chasm", floor: "basement", description: "A deep chasm splits the room.", effect: "Roll to cross: Speed 3+ to succeed. Failure ends your turn.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-coal-chute", editionId: "original", name: "Coal Chute", floor: "basement", description: "A steep slide covered in soot.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-crypt", editionId: "original", name: "Crypt", floor: "basement", description: "Stone coffins line the walls.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-dungeon", editionId: "original", name: "Dungeon", floor: "basement", description: "Iron chains hang from the walls.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-furnace-room", editionId: "original", name: "Furnace Room", floor: "basement", description: "A massive furnace radiates heat.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-pentagonal-room", editionId: "original", name: "Pentagonal Room", floor: "basement", description: "A room with five walls covered in strange symbols.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-stairs-from-basement", editionId: "original", name: "Stairs from Basement", floor: "basement", description: "Rickety stairs leading up.", effect: "Connects basement to ground floor.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-underground-lake", editionId: "original", name: "Underground Lake", floor: "basement", description: "A dark lake stretches into the shadows.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },

  // Rooms that can appear on multiple floors
  { id: "original-attic", editionId: "original", name: "Attic", floor: "upper", description: "A dusty attic full of forgotten things.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-conservatory", editionId: "original", name: "Conservatory", floor: "upper", description: "Dead plants fill this glass-walled room.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-larder", editionId: "original", name: "Larder", floor: "basement", description: "Shelves of preserved food, some of it moving.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-mystic-elevator", editionId: "original", name: "Mystic Elevator", floor: "ground", description: "An old elevator with a mind of its own.", effect: "Roll 2 dice. Move to the corresponding floor: 0=Basement, 1=Ground, 2=Upper.", hasEvent: false, hasItem: false, hasOmen: false },
  { id: "original-operating-laboratory", editionId: "original", name: "Operating Laboratory", floor: "upper", description: "An operating table with leather straps.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-statuary-corridor", editionId: "original", name: "Statuary Corridor", floor: "ground", description: "Statues line this hallway, their eyes seem to follow you.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-vault", editionId: "original", name: "Vault", floor: "basement", description: "A heavy door guards this room.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-creaky-hallway", editionId: "original", name: "Creaky Hallway", floor: "upper", description: "Every step makes the floor groan.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-bloody-room", editionId: "original", name: "Bloody Room", floor: "ground", description: "The walls are smeared with something dark.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
  { id: "original-dusty-hallway", editionId: "original", name: "Dusty Hallway", floor: "ground", description: "Thick dust covers everything.", effect: null, hasEvent: true, hasItem: false, hasOmen: false },
  { id: "original-graveyard", editionId: "original", name: "Graveyard", floor: "ground", description: "Headstones poke through the overgrown grass.", effect: null, hasEvent: false, hasItem: false, hasOmen: true },
  { id: "original-storeroom", editionId: "original", name: "Storeroom", floor: "basement", description: "Boxes and crates are stacked to the ceiling.", effect: null, hasEvent: false, hasItem: true, hasOmen: false },
];
